name: pipen
version: 2.2.1
homepage: 'https://library.pipen.dev'
description: "Essential development tools for great apps."
repository: 'https://github.com/juanfelipepipen/pipen-library'

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: any
  dio: ^5.4.1
  args: ^2.4.2
  mime: ^2.0.0
  http: ^1.2.2
  bloc: ^9.0.0
  meta: ^1.12.0
  async: ^2.11.0
  graphql: ^5.1.3
  lottie: ^3.0.0
  provider: ^6.1.2
  vibration: ^3.0.0
  go_router: ^15.0.0
  json_pretty: ^1.0.4
  http_parser: ^4.1.2
  file_picker: ^10.1.2
  cross_file: ^0.3.4+2
  flutter_bloc: ^9.0.0
  swipe_refresh: ^1.0.2
  flutter_skeleton_ui: ^0.0.6
  expandable_page_view: ^1.0.17
  flutter_secure_storage: ^9.0.0
  pipen_bloc: ^1.2.3
  uuid: ^4.5.1
  gql: ^1.0.1-alpha+1730759315362

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
